from . import (
    control4d_multiview,
    dreamfusion,
    fantasia3d,
    imagedreamfusion,
    # instructnerf2nerf,
    instructnerf2nerf_right,
    instructnerf2nerf_peterwz,
    latentnerf,
    magic3d,
    magic123,
    prolificdreamer,
    ours,
    sjc,
    textmesh,
    zero123,
    zero123_simple,
)
